### ISSUE TITLE
Cannot reproduce results on https://huggingface.co/spaces/multimodalart/flux-lora-the-explorer

### ISSUE THREAD

**Issue by mikebilly** [camenduru/flux.1-dev-lora-tost#1]
On your tost, [Text to Image] Flux.1 Dev + Loras, I use Xlabs Anime lora, and this prompt: 
"Portrait of a beautiful Asian woman with fox ears and long white hair, cosplaying as Ahri from League of Legends, She is surrounded by fox tails, which look like black fox-like creatures with glowing red eyes. The character has a red mark on her forehead and is making a graceful hand gesture, Red magical energy surrounds her. She has a red streak on her forehead and cheeks. Dark background with swirling red and yellow magical effects. The glowing red light creates a dramatic atmosphere. The woman's expression is serene and charming. High quality cosplay photo, sharp focus on the face, slight magical blur effect. Cinematic lighting, 8k resolution, high detail,
Style Cosplay photo, fantasy portrait, Immortalized Legend Ahri
Color palette: Main red, white, gold accents,
Dramatic lighting, red tint,
Mood Mysterious, intense, seductive,
Additional elements Magic particles, energy vortex,
Immortalized Legend Ahri character skin reference in League of Legends"

here is the job on Tost:
```
{"positive_prompt":"Portrait of a beautiful Asian woman with fox ears and long white hair, cosplaying as Ahri from League of Legends, She is surrounded by fox tails, which look like black fox-like creatures with glowing red eyes. The character has a red mark on her forehead and is making a graceful hand gesture, Red magical energy surrounds her. She has a red streak on her forehead and cheeks. Dark background with swirling red and yellow magical effects. The glowing red light creates a dramatic atmosphere. The woman's expression is serene and charming. High quality cosplay photo, sharp focus on the face, slight magical blur effect. Cinematic lighting, 8k resolution, high detail,\nStyle Cosplay photo, fantasy portrait, Immortalized Legend Ahri\nColor palette: Main red, white, gold accents,\nDramatic lighting, red tint,\nMood Mysterious, intense, seductive,\nAdditional elements Magic particles, energy vortex,\nImmortalized Legend Ahri character skin reference in League of Legends","seed":123,"steps":20,"guidance":3.5,"lora_file":"xlabs_anime.safetensors","lora_strength_model":1,"lora_strength_clip":1,"sampler_name":"euler","scheduler":"simple","width":1024,"height":1024}
```

But I get different result on https://huggingface.co/spaces/multimodalart/flux-lora-the-explorer. I want the results like on tost, how to replicate that? See the image below:
![image](https://github.com/user-attachments/assets/c8459eaf-372f-41e6-a8de-ce8547c99f26)

**Comment by camenduru** [comment]
<img width="1433" alt="image" src="https://github.com/user-attachments/assets/0b94e920-b54e-47e4-83f9-cbe7389cf891">

**Comment by mikebilly** [comment]
@camenduru Sorry, I sent the wrong picture, I used XLabs Anime but I took the wrong screenshot. The correct screenshot is below: 
![image](https://github.com/user-attachments/assets/cf7ca38b-a915-497e-9841-637d38b903c3)
![image](https://github.com/user-attachments/assets/b02372c4-9d38-40a9-9398-2a33e72ded41)

**Comment by mikebilly** [comment]
@camenduru please reopen this issue, I really want to recreate tost's results but haven't found the solution, please help me

**Comment by camenduru** [comment]
lora is here: https://huggingface.co/camenduru/FLUX.1-dev/blob/main/xlabs_flux_anime_lora.safetensors
